### ISSUE TITLE
pick() does not support @property properties 

### ISSUE THREAD

**Issue by m3talstorm** [dgilland/pydash#108]
**Example code:**

```
import pydash

class Test(object):

    @property
    def blah(self):
        return 5


test = Test()

print pydash.pick(test, 'blah')


class Test(object):

    def __init__(self):

        self.blah = 5


test = Test()

print pydash.pick(test, 'blah')

```
**Output:**

```
{}
{'blah': 5}
```

**Version:**

4.0.3

Is this intended? Haven't tested other descriptors.

**Comment by m3talstorm** [comment]
Looks like it uses the iterator helper function from [here](https://github.com/dgilland/pydash/blob/develop/pydash/helpers.py#L86) which in turn uses [this](https://github.com/dgilland/pydash/blob/develop/pydash/helpers.py#L97)

`getattr(obj, '__dict__', {})`

To access the object's properties, __dict__ does not return @property 's

**Comment by dgilland** [comment]
Excluding class properties was an explicit intention; they just weren't considered when support for iterating over class attributes was added. The original idea was to have a fairly lightweight way to exclude class methods.

But I'm not opposed to extending iteration to include class properties as well.
