### ISSUE TITLE
Better API documentation search

### ISSUE THREAD

**Issue by johngilden** [dgilland/pydash#109]
Hello Pydash,

love the project, great fan of lodash and see even more need for a library like this in Python-land.

My big issue right now is that the documentation is very hard to search / read in general, this is mostly due to the readthedocs UI. I'm sure you're aware of the excellent way of searching the lodash documentation, this feature alone makes me come back to this library every time. I'd appreciate it if lodash had a similarly easy-to-search API documentation. To outline what I mean, here is me searching for "get" in both search boxes.

![lodash](https://user-images.githubusercontent.com/10496846/33117243-fd2851b8-cf67-11e7-945c-db7e92f03597.png)
![pydash](https://user-images.githubusercontent.com/10496846/33117244-fd4417a4-cf67-11e7-8076-463b435545a3.png)

**Comment by brandonmp** [comment]
this could help

https://community.algolia.com/docsearch/

I've never used the service, but per the, err, docs, it's pretty simple: project owner submits the doc site URL, algolia crawls and indexes it, then you just drop into docs site
