### ISSUE TITLE
List inside object breaks objects.defaults_deep

### ISSUE THREAD

**Issue by meeech** [dgilland/pydash#113]
```pydash.objects.defaults_deep({}, {'elasticsearch': {'hosts': ['es-0.0.0.0:9200']}}, {'elasticsearch': {'hosts': ['1.0.0.0:9200']}})```

Throws an error. `AttributeError: 'list' object has no attribute 'setdefault'`
Expected result is the object contains - that it should treat the list as a 'whole' 

` {'elasticsearch': {'hosts': ['es-0.0.0.0:9200']}}`

python 3.6.3
pydash 4.3.1

**Comment by dgilland** [comment]
I have a potential fix for this. Going to try to get it done this week. Thanks for being patient!

**Comment by meeech** [comment]
Thanks @dgilland. I wanted to submit pr ( just doing a `hasattr(obj, 'setdefault')` check  in the setter), but i was having issues getting a working test after which covered the bug :/ - need to read up more on parametrize.  For now I'm getting around it with deep merge, but that also does a deep merge on a list, which is not desired behavior long term. 
Will the fix you looking at just treat lists like an object, or like a value?

**Comment by dgilland** [comment]
Initial idea was to do has you suggested and check for obj.setdefault in the setter. But I need to double check a few edge cases to confirm that’s all that’s needed.

**Comment by dgilland** [comment]
>  For now I'm getting around it with deep merge, but that also does a deep merge on a list, which is not desired behavior long term.
> Will the fix you looking at just treat lists like an object, or like a value?

The behavior of `defaults_deep` is that once a `list` is set, only dict objects within that `list` can updated but additional objects cannot be appended to it.

Some examples:

```python
pydash.defaults_deep({'a': [{}]}, {'a': [{'b': 'c'}]}) == {'a': [{'b': 'c'}]}
pydash.defaults_deep({'a': []}, {'a': [{'b': 'c'}]}) == {'a': []}
pydash.defaults_deep({'a': ['x']}, {'a': [{'b': 'c'}]}) == {'a': ['x']}
pydash.defaults_deep({'a': [{}]}, {'a': [{'b': 'c'}, {'e': 'f'}]}) == {'a': [{'b': 'c'}]}
pydash.defaults_deep({'a': [{}, {}]}, {'a': [{'b': 'c'}, {'e': 'f'}]}) == {'a': [{'b': 'c'}, {'e': 'f'}]}
```
