### ISSUE TITLE
Rename_keys should also take nested properties

### ISSUE THREAD

**Issue by anuragagarwal561994** [dgilland/pydash#116]
In the line:

https://github.com/dgilland/pydash/blob/97d8573bf019d124b6fe15b47a0ef5f94af8f38c/pydash/objects.py#L1159

python object getter is used, but if pydash getter is used instead we can also map nested properties like:
```python
{'a.b': 'c'}
```

**Comment by dgilland** [comment]
Care to submit a PR?

**Comment by anuragagarwal561994** [comment]
Surely I would love to help, but this is not as simple as I thought it would be. I avoided the point that the method has to return immutable object, that is why the whole dictionary is reconstructed.

But when I noticed again, I found that the method itself has a bug. Since it just copies the value part from the original object, if anything changes in the original `obj` will also change in the newly constructed `obj` too, making this method only half-immutable.

Example:
```python
from pydash import py_

obj = {'a': {'b': 1, 'c': 2}, 'd': 1}
n_obj = py_.rename_keys(obj, {'a': 'A', 'd': 'D'})
obj['a']['b'] = 2
obj['a']['b'] == n_obj['A']['b'] # will return True which is probably wrong if not expected behaviour
```
So there will be different approaches considering whether the method has to return mutable or immutable object. If immutable we will have to first do deep copy over the object and then we can simply use `py_.get`, `py_.set` and `py_.unset` to rename the keys.

**Comment by dgilland** [comment]
The `rename_keys` function isn't meant to return a deep-copy of the object, just a shallow one.

**Comment by anuragagarwal561994** [comment]
If that is the case then the whole dict need not be reconstructed and instead a bunch of `py_.get`, `py_.set` and `py_.unset` will do the job. Because the current implementation doesn't even return a shallow copy, it keeps the keys in the original object and returns new object with new keys.

**Comment by anuragagarwal561994** [comment]
Can you confirm what should be expected output of
`rename_keys({'a': {'b': 2 }, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'C'})`
Also if this is allowed
`rename_keys({'a': {'b': 2 }, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'A.C'})`

**Comment by dgilland** [comment]
The current implementation of `rename_keys()` *does* return a shallow copy (i.e. a new dict object is returned whose top-level keys can be modified without affecting the original):

```python
>>> from pydash import rename_keys
>>> obj = {'a': {'b': 1, 'c': 2}, 'd': 1}
>>> renamed = rename_keys(obj, {})
>>> renamed is obj
False
>>> for key in list(renamed.keys()): del renamed[key]
...
>>> renamed
{}
>>> obj
{'a': {'b': 1, 'c': 2}, 'd': 1}
>>> renamed = rename_keys(obj, {})
>>> for key in renamed: renamed[key] = True
...
>>> renamed
{'a': True, 'd': True}
>>> obj
{'a': {'b': 1, 'c': 2}, 'd': 1}
```

This is similar behavior as doing `renamed = obj.copy()`.

For:

> Can you confirm what should be expected output of `rename_keys({'a': {'b': 2}, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'C'})`
> Also if this is allowed `rename_keys({'a': {'b': 2}, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'A.C'})`

I would expect the following:

```python
>>> rename_keys({'a': {'b': 2 }, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'C'})
{'A': {'C': 2}, 'c': {'d': 3}}
>>> rename_keys({'a': {'b': 2 }, 'c': {'d': 3}}, {'a': 'A', 'a.b': 'A.C'})
{'A': {'A.C': 2}, 'c': {'d': 3}}
```

I think the idea here is that only the keys would be modified while the overall object structure would be the same.

Is that your expectation as well or did you have something else in mind?

**Comment by anuragagarwal561994** [comment]
Actually for the purpose I opened this issue, I was also looking for the change in structure as well, like it would be great to have a method in which you can probably do something like:
```python
>>> obj = {'a': {'b': 2 }, 'c': {'d': 3}}
>>> x = method(obj, {'a.b': 'c', 'c.d': 'e'})
>>> x == {'c': 2, 'e': 3}
True
```
But yes the above point make sense, `rename_keys` should not be allowed to change the structure of the object.

So if we are renaming keys of the sub elements as well, is it okay to assume that in the original object the keys will be modified too, since we are only returning the shallow copy:
```python
>>> obj = {'a': {'b': 2 }, 'c': {'d': 3}}
>>> renamed = rename_keys(obj, {'a': 'A', 'a.b': 'C'})
>>> renamed
{'A': {'C': 2}, 'c': {'d': 3}}
>>> obj
{'a': {'C': 2}, 'c': {'d': 3}}
```

There are still two approaches:
1. First make the shallow copy of the obj directly and then modify the keys with `get, set, unset`. The keys in the key_map needs to be sorted with depth first since the keys which are deep down the obj needs to be modified first before the keys that are on top. For sorting the keys I will need some help in looking for the edge cases.
2. Divide the key_map again as to make it easier to follow recursion and then recursively rename the keys, on every level it will give shallow copy of the object.

**Comment by dgilland** [comment]
For the method that would modify the object structure, I took a quick stab and something that sort of works (there are likely other edge cases where it returns the wrong result):

```python
def remap_keys(obj, key_map):
    marker = object()
    
    def rename(obj, target, source):
        value = get(obj, source, default=marker)
        
        if value is not marker:
            unset(obj, source)
            set_(obj, target, value)
            
    return transform(key_map, rename, clone_deep(obj))
```

I don't like that it uses `clone_deep` but it was the easiest way to avoid modifying `obj`. The return is a little different from yours, though:

```python
>>> obj = {'a': {'b': 2}, 'c': {'d': 3}}
>>> remap_keys(obj, {'c.d': 'e', 'a.b': 'c'})
{'a': {}, 'c': 2, 'e': 3}
>>> obj = {'a': {'b': 2, 'x': 4}, 'c': {'d': 3}}
>>> remap_keys(obj, {'c.d': 'e', 'a.b': 'c'})
{'a': {'x': 4}, 'c': 2, 'e': 3}
```

This is because `unset(obj, 'a.b')` just deletes the `a.b` key but leaves the rest of `a` unmodified.

For the "deep" `rename_keys` implementation, I believe something along these line would work:

```python
def rename_keys(obj, key_map):
    # Shallow copy obj so that top-level key renames won't modify original.
    new_obj = obj.copy()

    # Convert key_map into a list of two-element tuples containing the old key
    # path and the new key name sorted by deepest paths first. This is done so
    # that renames are performed bottom-up which avoids renaming higher level
    # keys before lower level ones which would result in a KeyError.
    key_map = sorted(((to_path(old), new) for old, new in key_map.items()),
                     key=lambda item: (-len(item[0]), tuple(item[0])))

    for keys, new in key_map:
        if not has(obj, keys):
            # Skip it if obj doesn't have key path.
            continue

        top = keys[0]

        if len(keys) > 1:
            # Case when a deep-path is being renamed. We'll descend down to the
            # next path level and perform rename recursively.
            new_obj[top] = rename_keys(new_obj[top], {'.'.join(keys[1:]): new})
        else:
            # Simple case where only the top-level key is being renamed.
            new_obj[new] = new_obj.pop(top)
    return new_obj
```

**Comment by anuragagarwal561994** [comment]
Remap keys in my opinion will have edge case problems depending on the object structure, also I think we can take that discussion to a new enhancement issue. So instead what I think would be useful method be not exactly remap keys but more of a combination of `py_.get` and `py_.pick`. Something like:
```python
def method(obj, key_map):
    new_obj = dict()
    for key, value in key_map:
        set(new_obj, value, get(obj, key)
    return new_obj
```
so usage example would look like:
```python
>>> obj = {'a': {'b': 2}, 'c': {'d': 3}}
>>> method(obj, {'a.b': 'A', 'c.d': 'C', 'a': 'B')
{'B': {'b': 2}, 'A': 2, 'C': 3}
```
This method can be useful in transforming to a flat object like:
```python
>>> obj = {'a': [{'c': 1, 'd': 2}, {'c': 3, 'd': 4}], 'b': 3}
>>> method(obj, {'a.[0]': 'first_a', 'b': 'B'})
{'first_a': {'c': 1, 'd': 2}, 'B': 3}
```
Still the above code is not full proof but just an example.

Coming back to the rename_keys method, when we are descending down recursively at every level we are creating a shallow copy right?
