### ISSUE TITLE
uniq functions time complexity

### ISSUE THREAD

**Issue by r7ar7a** [dgilland/pydash#118]
This implementation of uniq with the usage of arrays as the collection of seen items has clearly a (worst case) time complexity of O(n^2). However in case of input items are hashable, a linear implementation can be achieved by using a hashset here instead. Please make the method more efficient or at least add some warnings about this in the docstrings.

https://github.com/dgilland/pydash/blob/cb103ca6363cc5d497c116b11534aa18bf177a2f/pydash/arrays.py#L2291

```
import time
from datetime import datetime
import pydash as py_
s = datetime.now()
py_.uniq(range(10000))
t = datetime.now()
print(t-s)
```
`0:00:42.274382`

**Comment by dgilland** [comment]
I did a few minor modifications to see where the time issues are coming from and it seems that it's not so much the list data structure being used but the comparison between values that is taking up a majority of the time.

For example, on my machine, your perf test clocked in at about 24 seconds. When I replaced:

https://github.com/dgilland/pydash/blob/cb103ca6363cc5d497c116b11534aa18bf177a2f/pydash/arrays.py#L2297

with `if cmp_item == seen_item:`, then the time dropped to about 1.8 seconds. I tracked other inefficiencies down to `pydash.is_equal|is_equal_with`, but optimizing those didn't have as big of an impact. Even replacing:

https://github.com/dgilland/pydash/blob/cb103ca6363cc5d497c116b11534aa18bf177a2f/pydash/arrays.py#L2287

with `comparator = lambda a, b: a == b` took about 8 seconds.

Replacing:

https://github.com/dgilland/pydash/blob/cb103ca6363cc5d497c116b11534aa18bf177a2f/pydash/arrays.py#L2297

with:

```python
if comparator is None:
    was_seen = cmp_item == seen_item
else:
    was_seen = comparator(cmp_item, seen_item)

if was_seen:
    new = False
    break
```

yielded about 3.5 seconds.

After another pass-through, I was about to get the base case back down to about 1 second with the following implementation:

```python
def iterunique(array, comparator=None, iteratee=None):
    """Yield each unique item in array."""
    if not array:  # pragma: no cover
        return

    if iteratee is not None:
        iteratee = pyd.iteratee(iteratee)

    seen = []
    for item in array:
        if iteratee is None:
            cmp_item = item
        else:
            cmp_item = iteratee(item)

        if comparator is None:
            new = cmp_item not in seen
        else:
            new = True
            for seen_item in seen:
                if comparator(cmp_item, seen_item):
                    new = False
                    break

        if new:
            yield item
            seen.append(cmp_item)
```

Assuming that change doesn't break any tests, I can make that a part of the next release which should help improve the time complexity without losing any functionality (namely the customize comparator callback).

**Comment by r7ar7a** [comment]
You are right, this general functionality cannot be implemented with better asymptotic time complexity. 

However `uniq_by(array, iteratee=None)` uses the same implementation, but knowing that the comparator is out of the equation this can be implemented more efficiently somehow like this
```python
def uniq_by(array, iteratee=lambda x: x):
    seen_hashable = set()
    seen_unhashable = []
    for item in array:
        item_key = iteratee(item)
        if isinstance(item_key, collections.Hashable):
            if item_key not in seen_hashable:
                yield item
                seen_hashable.add(item_key)
        else:
            if item_key not in seen_unhashable:
                yield item
                seen_unhashable.append(item_key)
```

This issue get to me by some colleagues that used `uniq_by` as a blackbox alghorithm and we were surprised by the low speed. Actually some details about the performance in the docstring couldn't help us either, as they didn't read it, so it's only us to blame. :)
Anyway, if somebody needs a better method they can build it with ease specifically for their use case.

Thanks for the quick response anyway.

**Comment by r7ar7a** [comment]
> I'll also do some more to see about optimizing the comparator usage to also use the hasable/unhashable containers.

When custom comparator used, the function have to iterate through all the seen items, so I think no performance enhancement can be achieved.

**Comment by dgilland** [comment]
I was about to optimize a little for the custom comparator, at least for checking whether the item was previously yielded (assuming I didn't make any mistakes here):

```python
compare_to = None
try:
    if cmp_item not in seen_hashable:
        compare_to = seen_hashable
        add_using = seen_hashable.add
except TypeError:
    if cmp_item not in seen_unhashable:
        compare_to = seen_unhashable
        add_using = seen_unhashable.append

if compare_to is not None:
    unseen = True
    for seen_item in compare_to:
        if comparator(cmp_item, seen_item):
            unseen = False
            break

    if unseen:
        yield item
        add_using(cmp_item)
```

I haven't actually profiled this against the "unoptimized" custom comparator version so it might not offer much improvement but seems this version or previous would be the way to go.

**Comment by dgilland** [comment]
So with some very basic profiling, when dealing with a custom comparator with `range(10000)`, the time difference is almost 0: 7.62s "optimized" vs 7.85s "unoptimized". With `[1] * 10000`, the difference was 0.001s vs 0.002s. With `[{'a': 1}] * 10000`, it was 0.007s vs 0.002s. So the "optimized" doesn't seem to offer that much performance gain in some scenarios but definitely has more code complexity. So will go with the previous version that always uses the seen `list` for tracking.
