### ISSUE TITLE
pydash-4.7.2 ImportError: cannot import name callit

### ISSUE THREAD

**Issue by nmeisels** [dgilland/pydash#119]
updated pydash version to 4.7.2
when I try to run

`import pydash`

I get

`ImportError: cannot import name callit`

Python 2.7.14
System Version: OS X 10.11.6
Kernel Version: Darwin 15.6.0

**Comment by DemetriBairaktaris** [comment]
It looks like Python 2.7 support has been dropped for the latest 4.7.2 release.

**Comment by dgilland** [comment]
I mistakenly released from the wrong branch while working from my `v5` development branch. I've removed the `4.7.2` release from pypi and will be releasing `4.7.3` shortly which will continue to have Python 2.7 support.

**Comment by dgilland** [comment]
Released `4.7.3`: https://pypi.org/project/pydash/4.7.3/

**Comment by nmeisels** [comment]
It's working again.
Ok to close issue.
Thanks!
