### ISSUE TITLE
to_path treats lists and tuples differently

### ISSUE THREAD

**Issue by alexanderlukanin13** [dgilland/pydash#121]
It's surprising that [to_path treats lists and tuples differently](https://github.com/dgilland/pydash/blob/12571340029f75e03ad0c2d62fd8494423e59724/src/pydash/utilities.py#L1147)

Example:

    >>> import pydash
    >>> d = {'a': {'b': {'c': 42}}}
    >>> pydash.objects.get(d, ('a', 'b', 'c'))
    >>> pydash.objects.get(d, ['a', 'b', 'c'])
    42

It looks very un-pythonic to me.

If there is a reason behind this, it should be documented.

If it's a bug, I can make a pull request. It will require a new major release as it breaks backward compatibility. I think that using a single tuple as single key is a relatively rare use case: why would a person use pydash for that?

Also, as a more general duck-typing approach, I propose converting *anything* iterable, except strings, into a list. It can be done [here](https://github.com/dgilland/pydash/blob/12571340029f75e03ad0c2d62fd8494423e59724/src/pydash/utilities.py#L1230).

**Comment by dgilland** [comment]
This is by design. Consider:

```python
>>> d = {(1, 2): 3}
>>> pydash.get(d, (1, 2))
3
```

Tuples can be a valid dict-key so they are not treated like a path list. Lists, on the other hand, are not hashable so they cannot be used as a dict-key which is one of the reasons why that type was chosen as an alternative to string paths.

**Comment by alexanderlukanin13** [comment]
Yes, I understand. For me `pydash.get(d, (1, 2))` naturally translates to `pydash.get(d, [1, 2])` - but maybe that's just personal taste.

Actually, I've read some other functions, this design is consistent with the rest of the package, being picky about types is the rule (for example, you can't pass any iterable to `find`, only list or dict). But I still think that this caveat at least deserves mention in docs.

You can close this issue.
