### ISSUE TITLE
pydash.find fails with dict.values() on Python 3

### ISSUE THREAD

**Issue by xaralis** [dgilland/pydash#124]
When running `pydash.find` over `somedict.values()`, it fails with: `'dict_values' object does not support indexing` in Python 3. It is not a simple list but a [dictionary view object](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects). I would expect that pydash shall be able to browse through it anyway.

**Comment by dgilland** [comment]
Thanks for reporting! Fix is deployed in 4.7.5: https://pypi.org/project/pydash/4.7.5/
