### ISSUE TITLE
collections.count_by unhashable type dict

### ISSUE THREAD

**Issue by mikesmith37** [dgilland/pydash#130]
If I have an array of dictionaries, and want to count the number of instances that match each other can that be done using count_by?

e.g. [ {'a':1,'b':2},{'a':1,'b':1'},{'a':1,'b':2'}]
 
The result would be: [ {'a':1,'b':2}:2,{'a':1,'b':1'}:1]

If not what's the best approach (I have used a tuple but am looking for a cleaner way of doing this)

**Comment by dgilland** [comment]
`count_by` will return a dictionary mapping of unique values to their counts so the values need to be hashable.

You can use the `iteratee` argument to `count_by` to map the values, though. For example:

```python
>>> x = [{'a':1, 'b':2}, {'a':1, 'b':1}, {'a':1, 'b':2}]
>>> result = count_by(x, lambda d: tuple(d.items()))
>>> result
{(('a', 1), ('b', 2)): 2, (('a', 1), ('b', 1)): 1}
>>> for item, count in result.items(): print(dict(item), ":", count)
{'a': 1, 'b': 2} : 2
{'a': 1, 'b': 1} : 1
```
