### ISSUE TITLE
Use with Namespaces (or other plain python objects

### ISSUE THREAD

**Issue by greaber** [dgilland/pydash#133]
Hi, I was using argparse Namespaces as dict-like objects with a shorter, more JS-like syntax (at least when you don't dynamical values and have to use `getattr` and `setattr`).  It seems that with these values, I can use paths with pydash `get` but not with pydash `set`.  And `set_with` doesn't seem to help because it still wants to subscript the object (afaiu).  I was just wondering if there is a recommended solution to this issue.  Are there versions of the functions that work more like JS and don't work with dicts instead of POPOs?

**Comment by greaber** [comment]
Or maybe there are functions to convert between JS-style and dict-based objects?  I'm sure I could write it myself, but there might be corner cases, and this is the kind of thing I would like to turn to a library like pydash for

**Comment by dgilland** [comment]
Currently, `set` / `set_with` only supports setting dicts/lists.

The underlying function that sets is

https://github.com/dgilland/pydash/blob/1b4b425cecca275b8ba4c0584b40f9adae1cc097/src/pydash/helpers.py#L177-L203

which only handles dicts/lists and in `update_with`:

https://github.com/dgilland/pydash/blob/1b4b425cecca275b8ba4c0584b40f9adae1cc097/src/pydash/objects.py#L1669

which only supports item access.

It might be possible to add an `else` clause in there that would basically do `setattr(obj, key, value)`. So if `set_with` was given a `Namespace()` instance to modify and then `lambda: Namespace()` as the customizer.

And then update this:

https://github.com/dgilland/pydash/blob/1b4b425cecca275b8ba4c0584b40f9adae1cc097/src/pydash/objects.py#L1669

to `target = get(target, key)`.

Then that might work (assuming you want nested namespaces).

UPDATE:

Did the above locally and got the following results:

```python
>>> import pydash as pyd
>>> from argparse import Namespace
>>> customizer = lambda: Namespace()
>>> obj = Namespace()
>>> pyd.set_with(obj, "a.b", 5, customizer=customizer)
Namespace(a=Namespace(b=5))
>>> pyd.set_with(obj, "a.c.d", 55, customizer=customizer)
Namespace(a=Namespace(b=5, c=Namespace(d=55)))
```

Does that look like it'd cover your use-cases?

**Comment by greaber** [comment]
Yeah, this looks cool!  I think it would cover my use case although I don't know if there are other functions that would need to be changed for full support for this kind of thing.  Is this something you will consider adding to pydash?

**Comment by dgilland** [comment]
Yes, this is something I would add to pydash.
