### ISSUE TITLE
bug in 'sort_by'

### ISSUE THREAD

**Issue by seyoongit** [dgilland/pydash#143]
I'm using pydash **4.7.6** 

## test data

[{'a': 2, 'b': 0, 'c': 3, 'd': 5, 'e': 7},
 {'a': 3, 'b': 0, 'c': 0, 'd': 4, 'e': 0},
 {'a': 6, 'b': 1, 'c': 5, 'd': 8, 'e': 5},
 {'a': 7, 'b': 1, 'c': 9, 'd': 1, 'e': 4},
 {'a': 7, 'b': 1, 'c': 2, 'd': 5, 'e': 1},
 {'a': 1, 'b': 3, 'c': 9, 'd': 5, 'e': 7},
 {'a': 6, 'b': 3, 'c': 7, 'd': 9, 'e': 7},
 {'a': 7, 'b': 5, 'c': 3, 'd': 0, 'e': 3},
 {'a': 5, 'b': 6, 'c': 3, 'd': 3, 'e': 1},
 {'a': 5, 'b': 6, 'c': 8, 'd': 6, 'e': 3},
 {'a': 9, 'b': 7, 'c': 4, 'd': 4, 'e': 1},
 {'a': 3, 'b': 8, 'c': 4, 'd': 2, 'e': 4}]

#### it works well when execute with just single column ("a" in below case)
`_(aa).sort_by(["a"]).value()`

#### the result

[{'a': 1, 'b': 3, 'c': 9, 'd': 5, 'e': 7},
 {'a': 2, 'b': 0, 'c': 3, 'd': 5, 'e': 7},
 {'a': 3, 'b': 8, 'c': 4, 'd': 2, 'e': 4},
 {'a': 3, 'b': 0, 'c': 0, 'd': 4, 'e': 0},
 {'a': 5, 'b': 6, 'c': 3, 'd': 3, 'e': 1},
 {'a': 5, 'b': 6, 'c': 8, 'd': 6, 'e': 3},
 {'a': 6, 'b': 3, 'c': 7, 'd': 9, 'e': 7},
 {'a': 6, 'b': 1, 'c': 5, 'd': 8, 'e': 5},
 {'a': 7, 'b': 1, 'c': 9, 'd': 1, 'e': 4},
 {'a': 7, 'b': 5, 'c': 3, 'd': 0, 'e': 3},
 {'a': 7, 'b': 1, 'c': 2, 'd': 5, 'e': 1},
 {'a': 9, 'b': 7, 'c': 4, 'd': 4, 'e': 1}]

#### but went wrong when execute with multiple columns
`_(aa).sort_by(["a", "b"]).value()`

#### result (not sorted with "a", nor "b", just messy)
[{'a': 7, 'b': 1, 'c': 9, 'd': 1, 'e': 4},
 {'a': 6, 'b': 3, 'c': 7, 'd': 9, 'e': 7},
 {'a': 7, 'b': 5, 'c': 3, 'd': 0, 'e': 3},
 {'a': 3, 'b': 8, 'c': 4, 'd': 2, 'e': 4},
 {'a': 9, 'b': 7, 'c': 4, 'd': 4, 'e': 1},
 {'a': 3, 'b': 0, 'c': 0, 'd': 4, 'e': 0},
 {'a': 7, 'b': 1, 'c': 2, 'd': 5, 'e': 1},
 {'a': 6, 'b': 1, 'c': 5, 'd': 8, 'e': 5},
 {'a': 5, 'b': 6, 'c': 3, 'd': 3, 'e': 1},
 {'a': 2, 'b': 0, 'c': 3, 'd': 5, 'e': 7},
 {'a': 5, 'b': 6, 'c': 8, 'd': 6, 'e': 3},
 {'a': 1, 'b': 3, 'c': 9, 'd': 5, 'e': 7}]

#### ah, `order_by` just works well :)
`_(aa).order_by(["a", "b"]).value()`

[{'a': 1, 'b': 3, 'c': 9, 'd': 5, 'e': 7},
 {'a': 2, 'b': 0, 'c': 3, 'd': 5, 'e': 7},
 {'a': 3, 'b': 0, 'c': 0, 'd': 4, 'e': 0},
 {'a': 3, 'b': 8, 'c': 4, 'd': 2, 'e': 4},
 {'a': 5, 'b': 6, 'c': 3, 'd': 3, 'e': 1},
 {'a': 5, 'b': 6, 'c': 8, 'd': 6, 'e': 3},
 {'a': 6, 'b': 1, 'c': 5, 'd': 8, 'e': 5},
 {'a': 6, 'b': 3, 'c': 7, 'd': 9, 'e': 7},
 {'a': 7, 'b': 1, 'c': 9, 'd': 1, 'e': 4},
 {'a': 7, 'b': 1, 'c': 2, 'd': 5, 'e': 1},
 {'a': 7, 'b': 5, 'c': 3, 'd': 0, 'e': 3},
 {'a': 9, 'b': 7, 'c': 4, 'd': 4, 'e': 1}]

**Comment by dgilland** [comment]
The `sort_by(aa, ["a", "b"])` does not sort by keys "a" and "b" like `order_by` does. The `sort_by` function takes an iteratee while `order_by` takes a list of keys.

The `["a", "b"]` iteratee is the "matches property" style callback: https://pydash.readthedocs.io/en/latest/callbacks.html#matches-property-style
