### ISSUE TITLE
Have collections.includes search for dicts

### ISSUE THREAD

**Issue by altusgerona** [dgilland/pydash#145]
Currently, [collections.includes](https://pydash.readthedocs.io/en/latest/api.html#pydash.collections.at) only allows searching for values:
```sh
>>> includes({'a': 1, 'b': 2, 'c': 3, 'd': 4}, 2)
True
```
It should also allow for keys and dicts:
```sh
>>> includes({'a': 1, 'b': 2, 'c': 3, 'd': 4}, 'a')
True
>>> includes({'a': 1, 'b': 2, 'c': 3, 'd': 4}, {'a': 1})
True
```

**Comment by dgilland** [comment]
This behavior or `pydash.collections.includes` is by design in order to match how `lodash.includes` works.

There would be ambiguity if dictionaries were matched on either keys and values without a way to switch between the two.

There are already other functions that can do what you want, though:

```python
>>> from pydash import is_match, has
>>> has({'a': 1, 'b': 2, 'c': 3, 'd': 4}, 'a')
True
>>> is_match({'a': 1, 'b': 2, 'c': 3, 'd': 4}, {'a': 1})
True
```

**Comment by altusgerona** [comment]
Oh cool. Thanks for this. Missed it when I was looking at collection methods. Turns out it was a predicate.
