### ISSUE TITLE
kebabCase return empty string on Unicode strings

### ISSUE THREAD

**Issue by mervynlee94** [dgilland/pydash#149]
Lodash from Javascript has kebabCase that returns both ASCII and Unicode strings as expected. For pydash, the Unicode string as input will return an empty string for many functions such as kebabCase, upperCase, lowerCase, etc. I looked into the source code and realize this is due to not considering Unicode in the regex. Am I able to contribute to this project? Or anyone is able to implement that. Thanks!

**Comment by dgilland** [comment]
Contributions are welcome!

Feel free to submit a PR to fix this. It would be most appreciated! :+1:

**Comment by dgilland** [comment]
@mervynlee94 BTW, do you have an example to illustrate the issue? Also, what result do you get when you run the same with Lodash?

**Comment by mervynlee94** [comment]
Hi @dgilland, sorry for the late reply. Sure, one of the examples is "你好，世界", which is the translation of "Hello, World" in simplified Chinese. I am expected to get a result if 你好-世界 with kebabCase function, but get an empty string instead.

**Comment by dgilland** [comment]
Here's the lodash implementation:

- https://github.com/lodash/lodash/blob/e0029485ab4d97adea0cb34292afb6700309cf16/words.js#L32
- https://github.com/lodash/lodash/blob/e0029485ab4d97adea0cb34292afb6700309cf16/.internal/unicodeWords.js

Looks like they have a special Unicode version of the word splitter. Seems reasonable to implement something similar in pydash to achieve the desired results.

**Comment by mervynlee94** [comment]
Yes, I agreed. I will try to spare some time to implement it.

**Comment by mervynlee94** [comment]
@dgilland  

Referencing from Lodash implementation, the RE_WORDS in existing pydash is different from lodash, resulting in few failed test cases. 

Example of failing test case:

```
case = 'enable 24h format', expected = ['enable', '24', 'h', 'format']

    @parametrize(
        "case,expected",
        [  # noqa
            ("hello world!", ["hello", "world"]),  # noqa
            ("hello_world", ["hello", "world"]),
            ("hello!@#$%^&*()_+{}|:\"<>?-=[]\\;\\,.'/world", ["hello", "world"]),
            ("hello 12345 world", ["hello", "12345", "world"]),
            ("enable 24h format", ["enable", "24", "h", "format"]),
            ("tooLegit2Quit", ["too", "Legit", "2", "Quit"]),
            ("xhr2Request", ["xhr", "2", "Request"]),
            (" ", []),
            ("", []),
            (None, []),
        ],
    )
    def test_words(case, expected):
>       assert _.words(case) == expected
E       AssertionError: assert ['enable', '24h', 'format'] == ['enable', '2...'h', 'format']
E         At index 1 diff: '24h' != '24'
E         Right contains one more item: 'format'
E         Full diff:
E         - ['enable', '24', 'h', 'format']
E         ?               ----
E         + ['enable', '24h', 'format']

tests/test_strings.py:1189: AssertionError


```
It is due to the RE_WORDS
Existing: 
```
UPPER = "[A-Z\\xC0-\\xD6\\xD8-\\xDE]"
LOWER = "[a-z\\xDf-\\xF6\\xF8-\\xFF]+"
RE_WORDS = "/{upper}+(?={upper}{lower})|{upper}?{lower}|{upper}+|[0-9]+/g".format(
    upper=UPPER, lower=LOWER
)
```

Lodash's implementation
`RE_WORDS = "/[^\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\x7f]+/g"`

Which one should we follow?

**Comment by dgilland** [comment]
We should follow lodash's version. The version in pydash is somewhat out of date and hasn't been updated in awhile. So any failing test cases should be updated to match the new regex behavior that's in the latest lodash.

**Comment by mervynlee94** [comment]
Noted. I have implemented unicode and passed all the existing and new test cases in Python 3 versions. There are a lot of issues in Python 2 as they have different representation and implementation in strings and regex representation for unicode. Should we support Python 2.7?

**Comment by dgilland** [comment]
What types of errors are happening on Python 2 that aren't on 3? Is it just getting the test cases represented correctly or is there behavior difference in the function itself?

**Comment by mervynlee94** [comment]
The Unicode presentation is parsed consistently in Python 3 from the Javascript version, but in Python 2, it behaves differently, ended up with failing test cases.

**Comment by mervynlee94** [comment]
> What types of errors are happening on Python 2 that aren't on 3? Is it just getting the test cases represented correctly or is there behavior difference in the function itself?

Yes it is just getting the test cases represented correctly by the way ~

**Comment by mervynlee94** [comment]
@dgilland I guess if the new version of pydash is dropping the support for Python 2.7, can I just skip the tox test case environment of Python 2.7 and create a pull request?

**Comment by mervynlee94** [comment]
After investigation, there are some strange issue on Python 2.7. I have to use u'<the raw unicode regex> to solve one of the issue I raised in [Stackoverflow](https://stackoverflow.com/questions/65536859/different-behaviour-in-unicode-regex-for-python-2-and-python-3?noredirect=1#comment115868520_65536859) 

Another is the representation of string in Python 2 and Python 3 is different in nature. In Python 3, all strings are unicode but not in Python 2. Therefore the test cases won't match as it will output with raw `'\xe4', '\xe5', '\xef', '\xe4', '\xe7', '\xef'` instead of readable Unicode string.
