### ISSUE TITLE
pydash 4.9.1 can no longer get value on a dict object with int key using string notation

### ISSUE THREAD

**Issue by lephuongbg** [dgilland/pydash#157]
Following no longer works in pydash 4.9.1:

```python
assert pydash.get({1: {'name': 'John Doe'}}, '1.name') == 'John Doe'
```

This is most likely due to [this commit](https://github.com/dgilland/pydash/commit/3d963d2a0435186aec446c8eab53c43f34f763c4) that fixes #156 , due to the check with `dict.get` that doesn't preserve current behavior of pydash.

**Comment by dgilland** [comment]
Thanks for reporting this!

Should be fixed in [v4.9.2](https://pypi.org/project/pydash/4.9.2/).
