### ISSUE TITLE
set_ works unexpectedly when path is array and contains a `.`

### ISSUE THREAD

**Issue by killerdejavu** [dgilland/pydash#161]
```
obj = {}
_.set_(obj, ["something.is", "was"], 5)
```

Expected
```
obj = {
"something.is": {
  "was": 5
  }
}
```
Gives error `'NoneType' object has no attribute 'was'`

But works with lodash 

Also thanks for making pydash!

**Comment by dgilland** [comment]
What version of pydash are you using?

Looks like 4.8.0 has this bug but other versions before and after are ok.

This works as you describe with latest 4.9.3:

```python
>>> import pydash as _
>>> obj = {}
>>> _.set_(obj, ["something.is", "was"], 5)
{'something.is': {'was': 5}}
>>> obj
{'something.is': {'was': 5}}
```

**Comment by killerdejavu** [comment]
Thanks for the reply! Works after update.
