### ISSUE TITLE
pydash 5.0 can't be imported successfully in project (after update)

### ISSUE THREAD

**Issue by krisjobs681** [dgilland/pydash#162]
![image](https://user-images.githubusercontent.com/73709418/113112139-88135600-9211-11eb-8e90-5e479cbc3da1.png)
When I manually change the version to 4.9.3 in requirements.txt, everything works fine.

**Comment by dgilland** [comment]
Looks like you are using Python 3.5? That's no longer a supported version. Minimum is Python 3.6 for pydash 5.0.

**Comment by krisjobs681** [comment]
Remain blessed from all the cryptogods!
