### ISSUE TITLE
Improper verifying of param: "exceptions" in retry

### ISSUE THREAD

**Issue by gryznar** [dgilland/pydash#176]
In function retry there is auto conversion to tuple if parametr `exceptions` is instance of Exception:
```python
if isinstance(exceptions, Exception):  # pragma: no cover
    exceptions = (exceptions,) 
```

But this is improper from at least 2 reasons:
1. Documentation of this param says:
    """
    exceptions (tuple, optional): Tuple of exceptions that trigger a retry attempt. Exceptions
        not in the tuple will be ignored. Defaults to ``(Exception,)`` (all exceptions).
    """ <- single Exception is not mentioned here
2. Check itself. Should be:
```python
if issubclass(exceptions, Exception):  # pragma: no cover
    exceptions = (exceptions,) 
```

How it could be fixed:
1. Fix check and update documentation to mention single exception  class in possible values
OR
2. Remove this check and conversion

**Comment by dgilland** [comment]
Thanks for reporting!

I opted to just remove the check/conversion since it wasn't working and not documented to work anyway.
