### ISSUE TITLE
Missing dependency "typing_extensions"

### ISSUE THREAD

**Issue by BrutCZE** [dgilland/pydash#193]
Package "typing_extensions" is "part" of mypy package, but mypy is in dev dependencies.

![image](https://user-images.githubusercontent.com/34546098/231706862-ba7ae4dd-8b9d-4076-8880-644cec46f56a.png)

Can you add "typing_extensions" to regular dependencies please?

**Comment by dgilland** [comment]
Fixed in v7.0.1: https://pypi.org/project/pydash/7.0.1/

Thanks for reporting!
