### ISSUE TITLE
Zip type hinting and starmap

### ISSUE THREAD

**Issue by Drvanon** [dgilland/pydash#202]
For whatever reason, pylance does not recongnize zip as a method on the Chain object. 
```
Cannot access member "zip" for type "Chain[list[Hit]]"
```
This means that type hinting for chains using zip completely fails. 

Besides that, the workflow with zip is also very uncomfortable. For example in the following piece of code.

```python
plates = ["barcode1", "barcode 2"]
wells = [f"{row}{column} for row in "abcdefgh" for column in range(1, 13)]
hits = [("barcode3", "a4"), ("barcode3", "g5"), ("barcode4", "d2")]
movements = (
    py_(itertools.product(plates, wells))
    .zip(hits)
    .map(lambda tup: (tup[0][0], tup[0][1], tup[1][0], tup[1][1]))
    .value()
)
```

I would suggest a `starmap` method on chain that unpacks tuples to an iteratee.
```python
movements = (
    py_(itertools.product(plates, wells))
    .zip(hits)
    .starmap(lambda source, destination: (source[0], source[1], destination[0], destination[1]))
    .value()
)
```

The starmap method could look something like:

```python
def starmap(f: Func[[A, K], R], *args: A, **kwargs: K) -> R:
    return  f(*args, **kwargs)

class Chain:
    ...
    def starmap(self, f: Func[[?], R] -> Chain[R]):
        return wrap(f(self._value))
    ...
```

**Comment by dgilland** [comment]
Are you seeing the same issue when you use `pydash.zip_` directly with the same arguments that would be passed to the chained method call? Wondering if the typing issue is in the zip function *and* the chain zip method or just the chain method. FYI @DeviousStoat 

For starmap, you can do do that using `map` and `spread`:

```pydash
movements = (
    py_(itertools.product(plates, wells))
    .zip(hits)
    .map(py_.spread(lambda source, destination: (source[0], source[1], destination[0], destination[1])))
    .value()
)
```

**Comment by DeviousStoat** [comment]
There was a problem with the type stub generator script, it was skipping the functions with only vararg. So `zip` was not included along with some other functions.
https://github.com/dgilland/pydash/pull/203 This should fix it

**Comment by dgilland** [comment]
Fix for this has been released: https://pypi.org/project/pydash/7.0.6/
