### ISSUE TITLE
Typing call-overload error

### ISSUE THREAD

**Issue by mertcangokgoz** [dgilland/pydash#206]
I have a code like below, mypy keeps giving error but the parameters are correct. How can I fix this situation?

![image](https://github.com/dgilland/pydash/assets/8042604/a9ab6afb-2451-4de7-b02f-c1988e419ac6)

mypy error I get

![image](https://github.com/dgilland/pydash/assets/8042604/74b6bf91-8ecb-4d50-af0b-c5498816397b)

**Comment by dgilland** [comment]
From the mypy error, it looks like `self.used_assets` is being typed as `Any` by mypy. Does `self.used_assets` have a type hint set?

**Comment by mertcangokgoz** [comment]
@dgilland 

This is a jsonfield I use in django self.used_assets

**Comment by dgilland** [comment]
Is it lacking a type hint? That seems like what's happening, no type hint and can't be inferred so mypy gives it the `Any` type which then isn't compatible with `pydash.assign_with`. It looks like `used_assets` is `dict[str, int]` so I think `self.used_assets` just needs to have that type too.

**Comment by mertcangokgoz** [comment]
When I cast it as cast(dict[str, int], self.used_assets) there is no change. mypy keeps giving error. That's why I opened this issue.

**Comment by dgilland** [comment]
Oh, looks like there's a bug in your example:

```python
new_used_assets = pydash.assign_with(
    self.used_assets,
    used_assets,
    callback,
)
```

Should be:

```python
new_used_assets = pydash.assign_with(
    self.used_assets,
    used_assets,
    customizer=callback,
)
```

The `customizer` has to be passed as a keyword argument.
