### ISSUE TITLE
Map keys is broken

### ISSUE THREAD

**Issue by Drvanon** [dgilland/pydash#208]
When I call map_keys I expect the following behavior:

```python
from pydash import py_
assert py_(dict(a=1, b=2, c=3)).map_keys(lambda key: str.upper(key)).value() == dict(A=1, B=2, C=3)
```
but instead I get an error:
```
File ...\.venv\Lib\site-packages\pydash\chaining\chaining.py:48, in Chain.value(self)
     41 def value(self) -> Value_coT:
     42     """
     43     Return current value of the chain operations.
     44
     45     Returns:
     46         Current value of chain operations.
     47     """
---> 48     return self(self._value)

File ...\.venv\Lib\site-packages\pydash\chaining\chaining.py:108, in Chain.__call__(self, value)
     97 """
     98 Return result of passing `value` through chained methods.
     99
   (...)
    104     Result of method chain evaluation of `value`.
    105 """
    106 if isinstance(self._value, ChainWrapper):
    107     # pylint: disable=maybe-no-member
--> 108     value = self._value.unwrap(value)
    109 return value

File ...\.venv\Lib\site-packages\pydash\chaining\chaining.py:152, in ChainWrapper.unwrap(self, value)
    149 if wrapper._value is not UNSET:
    150     value = wrapper._value
--> 152 return wrapper.method(value, *wrapper.args, **wrapper.kwargs)

File ...\.venv\Lib\site-packages\pydash\objects.py:1205, in map_keys(obj, iteratee)
   1183 def map_keys(obj, iteratee=None):
   1184     """
   1185     The opposite of :func:`map_values`, this method creates an object with the same values as object
   1186     and keys generated by running each own enumerable string keyed property of object through
   (...)
   1203     .. versionadded:: 3.3.0
   1204     """
-> 1205     return {result: value for result, value, _, _ in iteriteratee(obj, iteratee)}

File ...\.venv\Lib\site-packages\pydash\objects.py:1205, in <dictcomp>(.0)
   1183 def map_keys(obj, iteratee=None):
   1184     """
   1185     The opposite of :func:`map_values`, this method creates an object with the same values as object
   1186     and keys generated by running each own enumerable string keyed property of object through
   (...)
   1203     .. versionadded:: 3.3.0
   1204     """
-> 1205     return {result: value for result, value, _, _ in iteriteratee(obj, iteratee)}

File ...\.venv\Lib\site-packages\pydash\helpers.py:108, in iteriteratee(obj, iteratee, reverse)
    105     items = reversed(tuple(items))
    107 for key, item in items:
--> 108     yield callit(cbk, item, key, obj, argcount=argcount), item, key, obj

File ...\.venv\Lib\site-packages\pydash\helpers.py:39, in callit(iteratee, *args, **kwargs)
     36 argcount = kwargs["argcount"] if "argcount" in kwargs else getargcount(iteratee, maxargs)
     37 argstop = min([maxargs, argcount])
---> 39 return iteratee(*args[:argstop])

Cell In[3], line 1, in <lambda>(key)
----> 1 py_(dict(a=1, b=2, c=3)).map_keys(lambda key: str.upper(key)).value()

TypeError: descriptor 'upper' for 'str' objects doesn't apply to a 'int' object
```

This is likely because when you call `iteriteratee` in the objects module:
```python
def map_keys(obj, iteratee=None):
    return {result: value for result, value, _, _ in iteriteratee(obj, iteratee)} 
```

`iteriteratee` calls like most iteratees with the values first and the keys second, but that is undesirable behavior for this function.

**Comment by zbynekcz12** [comment]
Yes, your analysis is correct. The `map_keys()` function in Pydash iterates over the object's keys and values in the order `(value, key)`, which is the opposite of the order that most iterators use. This is because the `map_keys()` function needs to know the key in order to generate the new key.

However, this order can cause problems if the iterator function expects the values to be strings. For example, the `str.upper()` function expects a string argument, but it will raise a TypeError if it is passed an integer.

To fix this, Pydash could change the order of the arguments in the `iteriteratee()` function to `(key, value)`. This would make the `map_keys()` function more consistent with other iterators and would also prevent the error that you are seeing.

In the meantime, there are a few workarounds that you can use. One option is to explicitly pass the `key` argument to the iterator function. For example:

```python
from pydash import py_

def upper_key(key):
    return key.upper()

assert py_(dict(a=1, b=2, c=3)).map_keys(upper_key).value() == dict(A=1, B=2, C=3)
```

Another option is to use a lambda function that takes the `key` and `value` arguments in the desired order. For example:

```python
from pydash import py_

assert py_(dict(a=1, b=2, c=3)).map_keys(lambda key, value: key.upper()).value() == dict(A=1, B=2, C=3)
```

Finally, you could also use a list comprehension to iterate over the object's keys and values and generate the new keys. For example:

```python
from pydash import py_

assert py_({key.upper(): value for key, value in dict(a=1, b=2, c=3).items()}).value() == dict(A=1, B=2, C=3)
```

I hope this helps!

**Comment by Drvanon** [comment]
Thank you for your quick response! I would like to point out that both your snippets fail:
```python
assert py_(dict(a=1, b=2, c=3)).map_keys(lambda key: key.upper()).value() == dict(A=1, B=2, C=3)
```
fails because the key argument is an integer. Your second snippet also does not work, since key and value need to be swapped:
```python 
from pydash import py_

assert py_(dict(a=1, b=2, c=3)).map_keys(lambda _value, key: key.upper()).value() == dict(A=1, B=2, C=3)
```
I agree that your third option does indeed work, however I really enjoy the way that I can use postfix notation on chains. It, so to say, breaks the chain.

**Comment by dgilland** [comment]
> `iteriteratee` calls like most iteratees with the values first and the keys second, but that is undesirable behavior for this function.

The behavior of `map_keys` has always been to pass `(value, key, object)` to the callback or the first N arguments if the callback accepts fewer than 3 arguments: https://github.com/dgilland/pydash/blob/64d4614fcfc4b1cc887f43b0446cc0d0746154c2/src/pydash/objects.py#L1183-L1187

This mirrors the behavior of Lodash's `mapKeys`: https://lodash.com/docs/4.17.15#mapKeys
