### ISSUE TITLE
max_by should return max value, not object

### ISSUE THREAD

**Issue by stephanelsmith** [dgilland/pydash#209]
From lodash
https://lodash.com/docs/#maxBy

This would also be consistent with sum_by, mean_by, etc...

**Comment by dgilland** [comment]
I'm not sure I follow since the examples on https://lodash.com/docs/#maxBy have objects being returned which is what pydash does too when a list of objects is passed in.

**Comment by stephanelsmith** [comment]
You're right...  it seems inconsistent to me in lodash.  The returns documentation a bit different from the example.

Sorry about that.  I love this library btw.

**Comment by stephanelsmith** [comment]
You're right... it seems inconsistent to me in lodash. The returns documentation a bit different from the example. Sum_by, mean_by, etc... return just the value. Min_by is like max_by. Weird....

Sorry about that. I love this library btw.

**Comment by dgilland** [comment]
No worries! Glad you've found library useful!
