### ISSUE TITLE
Use ruff

### ISSUE THREAD

**Issue by DeviousStoat** [dgilland/pydash#219]
Would you be open for a PR switching all the lint and formatting tools to use [ruff](https://github.com/astral-sh/ruff) instead?

It does what `flake8`, `pylint`, `isort` and `black` does in a single tool and it is a lot faster. After getting used to it I often get a bit annoyed at how slow `pylint` is.

**Comment by dgilland** [comment]
Yes, `ruff` would be most welcomed!

Would also be nice to move tool configs from `setup.cfg` to `pyproject.toml`. The ultimate goal being to drop `setup.py` and `setup.cfg` in favor of defining the project metadata/build-info in `pyproject.toml` using setuptools's https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html.
