### ISSUE TITLE
Strange warning when importing pydash.get in PyCharm.

### ISSUE THREAD

**Issue by huypxgear** [dgilland/pydash#227]
I got a strange warning when importing `pydash.get` in PyCharm. 

Code:
`schedules = offer.get('schedules', None)`

Warning:

`Fixture 'offer.get' is not requested by test functions or @pytest.mark.usefixtures marker`

**Comment by dgilland** [comment]
How is `offer` define?

There are several PyCharm bugs reported about similar warnings:

- https://youtrack.jetbrains.com/issue/PY-70463
- https://youtrack.jetbrains.com/issue/PY-65960
- https://youtrack.jetbrains.com/issue/PY-65351
- https://youtrack.jetbrains.com/issue/PY-34498

**Comment by huypxgear** [comment]
>How is offer define?

it is just a normal dict like that
`offer = {'test': {}}`

The strange thing is that the warning only appears when importing `pydash.get`. If I remove the import line, the warning disappears.

**Comment by dgilland** [comment]
> I guess it might be a PyCharm issue, confusing dict.get with pydash.get

That seems to track with what other are reporting in the JetBrains tickets.
