### ISSUE TITLE
merge method logic bugs

### ISSUE THREAD

**Issue by travelcode** [dgilland/pydash#229]
test code:

>    dict1={"a":1,"b":{"c":3,"d":4,"e":{"f":5,"g":6},"h":[0,1,2,3,4]}}
>    dict2 = {"i": 7, "b": {"c": 3, "d": 5, "e": {"f": 5, "g": 6,"x":10}, "h": [3,4,5,6]},"j":{"k":8,"l":9}}
>    dict3={"m":[10,11,12,13]}
>    merged_dict = merge({}, dict1, dict2,dict3)
>    print(json.dumps(merged_dict))
output:

> {"a": 1, "b": {"c": 3, "d": 5, "e": {"f": 5, "g": 6, "x": 10}, "h": [3, 4, 5, 6, 4]}, "i": 7, "j": {"k": 8, "l": 9}, "m": [10, 11, 12, 13]}
the "h" field value is error: [3, 4, 5, 6, 4],real output should [0,1,2,3,4,3,4,5,6] or [0,1,2,3,4,5,6] or  [3,4,5,6],but output [3, 4, 5, 6, 4],This is why?

**Comment by spider-man-tm** [comment]
@travelcode 
I believe this issue pertains to a similar topic. Kindly refer to it for your reference.
#158
