### ISSUE TITLE
Shouldn't string functions be None-safe?

### ISSUE THREAD

**Issue by k7sleeper** [dgilland/pydash#44]
I found that string functions aren't consistently `None`-safe, i.e. `trunc`, `camel_case`, ... are `None`-safe but `explode` and others aren't.

I propose string functions to be `None`-safe as is in [Apache Commons Lang](http://commons.apache.org/proper/commons-lang/javadocs/api-release/index.html) and in [underscore.string](https://github.com/epeli/underscore.string).

I also propose: `_.to_string(None)` returns `''` instead of `'None'` actually.

**Comment by dgilland** [comment]
This sounds reasonable. I think a good approach would be to call `to_string` on all `text` arguments where a string is expected. `to_string` could be modified to convert `None` to `''`.

A decorator implementation would be one way to easily convert the `text` argument assuming it's always the first argument. I believe most of the string functions have `text` as the first argument except the regexp functions but those function signatures could be modified to be consistent with the other string functions.

This is sounding like a mostly backwards incompatible change so would be best to put these in a `v3` release. I've also added porting the [underscore.string](https://github.com/epeli/underscore.string) enhancement (#39) to [v3](https://github.com/dgilland/pydash/milestones/v3.0.0).

**Comment by k7sleeper** [comment]
May I create a PR for this feature or do I have to wait until MS 3 development begins?

**Comment by dgilland** [comment]
I've created a new branch: [feature-v3](https://github.com/dgilland/pydash/tree/feature-v3). You can submit any PRs related to this feature there.

**Comment by dgilland** [comment]
@k7sleeper Any progress on this? I'm wrapping up the main port of `underscore.string` which will close the majority of the work for `v3`.

**Comment by k7sleeper** [comment]
Unfortunately not, I didn't find the time but I hope that'll change the next days.

**Comment by dgilland** [comment]
No worries. I've gone ahead with making all of the string functions `None`-safe; the changes were pretty trivial.

**Comment by k7sleeper** [comment]
Well I just created #46. Hope that's ok!?

**Comment by dgilland** [comment]
Yes, #46 is fine. Test cases are good which I haven't got around to yet.

**Comment by dgilland** [comment]
Closed via e61109166ae2009287b73007914c986393ea412d.

**Comment by dgilland** [comment]
Reopening since I closed it prematurely. There is still more work to do to fully implement this.

**Comment by dgilland** [comment]
Wrapped up via 3a454cfd3b12bf06f89ca9438b2a76630f935542.
