### ISSUE TITLE
This library is amazing

### ISSUE THREAD

**Issue by samy100** [dgilland/pydash#59]
I do a lot of development using lodash and lodash-fp. I got to say, this library is a godsend for similar functionality in Python. It makes porting existing lodash-centric logic a lot easier as well. I hope this project doesn't die. Is there some sort of established relationship with lodash itself? We should promote the use of this more.
Thanks for your efforts :+1:

**Comment by dgilland** [comment]
Hi, thanks for the kind words!

This project isn't dead but work has slowed as I don't have as much free time to devote to open source like I used to. The last pydash "sync" with lodash was back in Sept 2015 with lodash [v3.10.0](https://github.com/lodash/lodash/wiki/Changelog#v3100). Looks like lodash is now at v4.5.0. So I'm sure there a lot of changes that could be ported into pydash. I'm always open to contributions :smile:.

I don't have an established relationship with lodash. I mainly started this project on my own to help with Python experience and learning how to maintain and distribute Python libraries.

**Comment by SoaringTiger** [comment]
:+1:
