### ISSUE TITLE
Why does pydash have map_?

### ISSUE THREAD

**Issue by HannesHolste** [dgilland/pydash#63]
Hi there,

Great work on this library, super useful as someone who comes from the JS lodash world.

I was wondering why pydash duplicates in-built functions such as map, given that pydash equivalents are significantly slower when benchmarked with `%timeit` in ipynb.

**Comment by dgilland** [comment]
The callback system for pydash doesn't work the same way as callbacks passed to `map()`:

```python
>>> import pydash
>>> items = [1, 2, 3, 4]
>>> callback = lambda val: val * 2
>>> list(map(callback, items))
[2, 4, 6, 8]
>>> pydash.map_(items, callback)
[2, 4, 6, 8]
>>> import pprint
>>> callback = lambda item, key, obj: (item, key, obj)
>>> pprint.pprint(pydash.map_(items, callback))
[(1, 0, [1, 2, 3, 4]),
 (2, 1, [1, 2, 3, 4]),
 (3, 2, [1, 2, 3, 4]),
 (4, 3, [1, 2, 3, 4])]
>>> callback = lambda item, key, obj: (item, key)
>>> pydash.map_(items, callback)
[(1, 0), (2, 1), (3, 2), (4, 3)]
```

You can also do things like:

```python
items = [{'a': 1}, {'a': 2}, {'a': 3}, {'a': 4}]
>>> pydash.map_(items, 'a')
[1, 2, 3, 4]
>>> pydash.map_(items, {'a': 1})
[True, False, False, False]
>>> pydash.map_(items, {'a': 2})
[False, True, False, False]
>>> pydash.map_(items, {'a': 3})
[False, False, True, False]
>>> pydash.map_(items, {'a': 4})
[False, False, False, True]
```

Basically you can pass in a callbacks with differing number of args (and as objects or strings) and pydash will call them appropriately (this is done to simulate the JS-style function arguments and to make it easier to use builtins without having to define wrappers [e.g. ``pydash.map(items, lambda value, *args: str(value))`` vs ``pydash.map(items, str)``]. Originally pydash required all callbacks to have the correct number of args but I decided to relax that requirement to make the callbacks easier to use while sacrificing performance.

The slowness in pydash typically comes from the callback system. You can read some discussion on that in #58 along with some changes that were done at the time to address some of the performance issues. I'm open to other ideas around improving performance though.

Btw, what was the benchmark you used for `timeit`?

**Comment by HannesHolste** [comment]
Thank you for your detailed response, @dgilland, that was very illuminating. Feel free to close this issue.

Here's what I did in jupyter notebook:
```
jupyter console
In [1]: import numpy as np

In [2]: import pydash

In [3]: a = np.arange(0, 100000, 1)

In [4]: %timeit map(lambda x: x, a)
100 loops, best of 3: 14.1 ms per loop

In [5]: %timeit pydash.map_(a, lambda x: x)
10 loops, best of 3: 105 ms per loop
```
