### ISSUE TITLE
Add LoDash functions

### ISSUE THREAD

**Issue by bharadwajyarlagadda** [dgilland/pydash#66]
## Arrays
- [x] `difference_by`
- [x] `difference_with`
- [x] `flatten_depth`
- [x] `from_pairs`
- [x] `intersection_by`
- [x] `intersection_with`
- [x] `nth`
- [x] `pull_all`
- [x] `pull_all_by`
- [x] `pull_all_with`
- [x] `sorted_index_by`
- [x] `sorted_index_of`
- [x] `sorted_last_index_by`
- [x] `sorted_last_index_of`
- [x] `sorted_uniq`
- [x] `sorted_uniq_by`
- [x] `union_by`
- [x] `union_with`
- [x] `uniq_by`
- [x] `uniq_with`
- [x] `xor_by`
- [x] `xor_with`
- [x] `zip_object_deep`

## Collections
- [x] `flat_map`
- [x] `flat_map_deep`
- [x] `flat_map_depth`
- [x] `invoke_map`
- [x] `sample_size`

## Objects
- [x] `assign_with`
- [x] `clone_deep_with`
- [x] `clone_with`
- [x] `invert_by`
- [x] `merge_with`
- [x] `omit_by`
- [x] `pick_by`
- [x] `set_with`
- [x] `to_integer`
- [x] `unset`
- [x] `update`
- [x] `update_with`

## Predicates
- [x] `eq`
- [x] `is_equal_with`
- [x] `is_match_with`
- [x] `is_set`

## Strings
- [x] `lower_case`
- [x] `lower_first`
- [x] `upper_case`
- [x] `upper_first`
- [x] `to_lower`
- [x] `to_upper`

## Numerical
- [x] `clamp`
- [x] `mean_by`
- [x] `max_by`
- [x] `min_by`
- [x] `sum_by`
- [x] `subtract`
- [x] `divide`
- [x] `multiply`

## Functions
- [x] `flip`
- [x] `unary`

## Utilities
- [x] `cond`
- [x] `conforms`
- [x] `conforms_to`
- [x] `default_to`
- [x] `nth_arg`
- [x] `over`
- [x] `over_every`
- [x] `over_some`
- [x] `range_right`
- [x] `stub_array` (or maybe `stub_list`?)
- [x] `stub_object` (or maybe `stub_dict`?)
- [x] `stub_string`
- [x] `stub_false`
- [x] `stub_true`
- [x] `to_path`

**Comment by dgilland** [comment]
All of these functions have been added now.
