### ISSUE TITLE
ValueError: invalid literal for int() with base 10 in get

### ISSUE THREAD

**Issue by urbnjamesmi1** [dgilland/pydash#76]
Operating System: MacOS X 10.11.5 (El Capitan)
Python versions: 2.7, 3.4, 3.5
Pydash version: 3.4.5
Reproduction steps:

1. In a Python virtualenv with pydash as a pip dependency, open a Python REPL and enter:
```
import pydash
a = { 'a': { 'b': { 'c': { 'd': [] } } } }
pydash.get(a, 'a.b.e.d', [])
``` 
2. You will get a TypeError stating that list indices must be integers, not str, followed by:
```
ValueError: invalid literal for int() with base 10: 'd'
```

It should have returned the default value `[]`

**Comment by dgilland** [comment]
I've release this fix as `v3.4.6`: https://pypi.python.org/pypi/pydash/3.4.6

Thanks again for the patch, @urbnjamesmi1!
