### ISSUE TITLE
When get_item returns the default value, pydash.objects.get continues evaluating the key path

### ISSUE THREAD

**Issue by urbnjamesmi1** [dgilland/pydash#78]
If the remaining keys are in the default value, you'll get the value inside the default value supplied to get instead of the default value itself.

Operating System: Mac OS X 10.11.5 (El Capitan)
Steps to reproduce:

1. In a python REPL with pydash installed, type:
```
import pydash

obj = {'one': {'two': {'three': 4}}}
default_value = [{'a': 1}]
value = pydash.get(obj, 'one.four.0.a', default=default_value)
value
```

2. `value` will be 1 instead of `[{'a': 1}]` because while processing the 'four' key, get_item returns the default value and get continues with '0.a'

**Comment by dgilland** [comment]
Awesome work finding this! Really appreciate it! :+1: 

I've released the fix as `v3.4.7`: https://pypi.python.org/pypi/pydash/3.4.7
