### ISSUE TITLE
py_.intersection returns an empty set if no *others are given

### ISSUE THREAD

**Issue by efenka** [dgilland/pydash#93]
This is a difference between 4.0.1 and 3.4.8 that i cannot really resolve.

    $ pip install pydash==3.4.8
    >>> py_.intersection([1, 2, 3], [1, 2])
    [1, 2]
    >>> py_.intersection([1, 2, 3])
    [1, 2, 3]

And now:

    $ pip install pydash==4.0.1
    >>> py_.intersection([1, 2, 3], [1, 2])
    [1, 2]
    >>> py_.intersection([1, 2, 3])
    []

I call `py_.intersection` with a set of arrays like `common_values = py_.intersection(*list_of_lists)`, so i run into this problem if my list_of_lists contains only a single list.

**Comment by dgilland** [comment]
Good catch! :+1: 

This has been fixed in `v4.0.2`: https://pypi.python.org/pypi/pydash/4.0.2
