### ISSUE TITLE
Concatenating None

### ISSUE THREAD

**Issue by bustawin** [dgilland/pydash#95]
Concatenating when source is `None` produces the following:
```python
pydash.concat(None, [1]) == [None,1]
```
The expected output is:
```python
pydash.concat(None, [1]) == [1]
```

Happens in Pydash 3.4.8 and 4.0.3 under macOS 10.12.4, Python 3.4.

PS: magnificent library!

**Comment by dgilland** [comment]
The `concat` function isn't meant to remove falsey (or `None`) values. This mirrors the implementation in Lodash:

```node
> require('lodash').concat(null, [1]);
[ null, 1 ]
```

If you want to remove all falsey values, then you can do:

```python
>>> pydash.compact(pydash.concat(None, [1], False))
[1]
```

If you only want to remove `None` values then:

```python
>>> pydash.filter_(pydash.concat(None, [1], False), lambda item: item is not None)
[1, False]
```
