### ISSUE TITLE
object:get, documentation describes the other behavior from lodash

### ISSUE THREAD

**Issue by maxkoryukov** [dgilland/pydash#99]
Hello!

Documentation for `get` method differs from the docs for an appropriate method of **lodash**.

[Lodash get](https://lodash.com/docs/4.17.4#get):

```js
var object = { 'a': [{ 'b': { 'c': 3 } }] };
_.get(object, 'a[0].b.c');
// => 3
```

[Pydash get](http://pydash.readthedocs.io/en/latest/api.html#pydash.objects.get):

```python
get({'a': {'b': {'c': [1, 2, 3, 4]}}}, 'a.b.c.1')
# => 2
```

As you could see, list/array access differs (`a[0].b.c` vs `a.b.c.1`). But original lodash syntax works as expected:

```python
get({'a': {'b': {'c': [1, 2, 3, 4]}}}, 'a.b.c[1]')
# => 2
```

The point is to update docs (because it is a little bit confusing now)

Thank you!

**Comment by dgilland** [comment]
Thanks for the suggestion! :+1:
